//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrador
    {
        public decimal Adm_Id { get; set; }
        public string Adm_nom { get; set; }
        public string Adm_ape { get; set; }
        public string Adm_dir { get; set; }
        public string Adm_tel { get; set; }
        public string Adm_cor { get; set; }
        public string Adm_usu { get; set; }
        public string Adm_con { get; set; }
    }
}
