//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public decimal Cli_id { get; set; }
        public string Cli_Nom { get; set; }
        public string Cli_Dir { get; set; }
        public string Cli_Tel { get; set; }
        public string Cli_Cor { get; set; }
        public string Cli_Usu { get; set; }
        public string Cli_Con { get; set; }
        public string Cli_Est { get; set; }
    }
}
