//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public decimal Prod_Id { get; set; }
        public Nullable<int> Prod_Uni { get; set; }
        public Nullable<int> Prod_Precio { get; set; }
        public string Prod_Nombre { get; set; }
        public string Prod_Descripcion { get; set; }
    }
}
