//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        public decimal Prov_nit { get; set; }
        public string Prov_Nom { get; set; }
        public string Prov_Ape { get; set; }
        public string Nom_Emp { get; set; }
        public string Prov_Dir { get; set; }
        public string Prov_Tel { get; set; }
        public string Prov_Cor { get; set; }
    }
}
